### ISSUE TITLE
T: Base de Datos

### ISSUE THREAD

**Issue by yamilcba** [PPROF1-2021/g1-periodicodigitalestudiantil#51]
Construir la Base de Datos Relacional del sitio, estableciendo tablas, relaciones y cardinalidad.  
1) Modelo de Datos relacional de acuerdo al modelo de negocio.
2) Generar el Script DDL para crear la base de datos con las tablas identificadas.
3) Definir las consultas a la base de datos. 
4) Armar las bases de los campos estándar.

Esta etapa no incluye la vinculación.

**Comment by KevinArceKessler** [comment]
BASE DE DATOS:
https://github.com/PPROF1-2021/g1-periodicodigitalestudiantil/blob/Master/ScriptBuenasNuevas.txt

CONSULTAS VARIAS:
https://github.com/PPROF1-2021/g1-periodicodigitalestudiantil/blob/Master/ConsultasBuenasNuevas.txt
